# This is the basic workflow to build draft documentation

name: Snapshot Build
## This section contains ALL variable specific for this project ##
# The VERSION is the main release number i.e. 1.7 or 2.1
env:
  BUILD_NAME:           PrintTalk
  DOCUMENT_VERSION:     '2.2'
  DOCUMENT_COVER_TITLE:   PrintTalk Specification
  CONFIG_FILE:          Build\PrintTalk.ini
  CONFLUENCE_ID:        '1560313992'
  CONFLUENCE_LABELS:    'printtalk-specification,spec-draft'  
  
  DOCUMENT_METADATA_COPYRIGHT:  'CIP4 Organization, all rights reserved'
  DOCUMENT_METADATA_TITLE:      'PrintTalk Specification'
  DOCUMENT_METADATA_SUBJECT:    'Communication of Business Transactions Between Print Buyers and Print Providers'
  DOCUMENT_METADATA_AUTHOR:     'CIP4 Organization'
  DOCUMENT_METADATA_KEYWORDS:   'Automation;CIM;CIP4;Exchange Job Definition Format;Graphic Arts;Graphics;ICS;Interface;Interoperability;Interoperability Conformance;Specification;Printing;PrintTalk;Specification;Standard;Workflow;XJDF;XJMF;XML'

  BUILD_UTILITY_EXE: c:\actions-runner\_work\_tool\document-processing\document-processing.exe  

## The remaining section SHOULD be common to all draft documentation builds
# Controls when the action will run
on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual Run'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: [framemaker-2020]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # For access to other Git repositories - an access token is required. 
      - name: Get GitHub Access Token
        id: access_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CIP4_GITHUB_ACTIONS_APP_ID }}
          private_key: ${{ secrets.CIP4_GITHUB_ACTIONS_APP_KEY }} 
      
      # Clean up working directory
      - name: Clean up working directory
        run:  rm -r -fo *
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: document

      # Check out the build scripts
      - name: Checkout build scripts
        uses: actions/checkout@v2
        with:
          repository: cip4/cip4-document-builder
          token: ${{ steps.access_token.outputs.token }}
          path: builder

      # Build the document parameters
      - name: Build Document
        timeout-minutes: 30
        run: >
          python ..\builder\scripts\specbuilder.py $env:CONFIG_FILE
          "$env:DOCUMENT_COVER_TITLE $env:DOCUMENT_VERSION Draft $((Get-Date).ToString('yyyyMMdd')) Build-$env:GITHUB_RUN_NUMBER"
          "$env:DOCUMENT_COVER_TITLE"
          "$env:DOCUMENT_VERSION Draft $((Get-Date).ToString('yyyyMMdd')) Build-$env:GITHUB_RUN_NUMBER"
          "Run-$env:GITHUB_RUN_NUMBER"
        working-directory: ./document
        
      # Mark pages with draft watermark
      - name: Watermark pages
        run: >
          ${{ env.BUILD_UTILITY_EXE }} draft "$env:DOCUMENT_COVER_TITLE*.pdf"
        working-directory: ./document/target
        
      # Update document meta-data properties
      - name: Update Document Metadata
        run: >
          ${{ env.BUILD_UTILITY_EXE }} info "$env:DOCUMENT_COVER_TITLE*.pdf"
          --copyright "$((Get-Date).ToString('MMMM yyyy')) $env:DOCUMENT_METADATA_COPYRIGHT"
          --title     "$env:DOCUMENT_METADATA_TITLE $env:DOCUMENT_VERSION Draft $((Get-Date).ToString('yyyyMMdd')) Build-$env:GITHUB_RUN_NUMBER" 
          --subject   "$env:DOCUMENT_METADATA_SUBJECT"
          --author    "$env:DOCUMENT_METADATA_AUTHOR"
          --keywords  "$env:DOCUMENT_METADATA_KEYWORDS"
          --version   "$env:DOCUMENT_VERSION Draft $((Get-Date).ToString('yyyyMMdd')) Build-$env:GITHUB_RUN_NUMBER"
        working-directory: ./document/target
        
      # Upload any artefact produced.
      - name: Upload Document
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}-artifact
          path: document/target/*.pdf
          
      # Upload to Confluence
      - name: Confluence Upload
        uses: cip4/action-confluence-upload@master
        with:
          url: 'https://cip4.atlassian.net/wiki'
          username: ${{ secrets.ATLASSIAN_USER }}
          password: ${{ secrets.ATLASSIAN_TOKEN }}
          contentId: ${{ env.CONFLUENCE_ID }}
          label: ${{ env.CONFLUENCE_LABELS }}
          filePattern: 'document/target/*.pdf'
