# This is the basic workflow to build draft documentation

name: Snapshot Build
## This section contains ALL variable specific for this project ##
# The VERSION is the main release number i.e. 1.7 or 2.1
env:
  BUILD_NAME:           PrintTalk
  DOCUMENT_VERSION:     '2.2'
  DOCUMENT_FILE_NAME:   PrintTalk
  CONFIG_FILE:          Build\PrintTalk.ini
  CONFLUENCE_ID:        '15663320'
  CONFLUENCE_LABELS:    'ptk-specificaion,spec-draft'  

## The remaining section SHOULD be common to all draft documentation builds
# Controls when the action will run
on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual Run'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: [framemaker-2020]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # For access to other Git repositories - an access token is required. 
      - name: Get GitHub Access Token
        id: access_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CIP4_GITHUB_ACTIONS_APP_ID }}
          private_key: ${{ secrets.CIP4_GITHUB_ACTIONS_APP_KEY }} 
      
      # Clean up working directory
      - name: Clean up working directory
        run:  rm -r -fo *
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: document

      # Check out the build scripts
      - name: Checkout build scripts
        uses: actions/checkout@v2
        with:
          repository: cip4/cip4-document-builder
          token: ${{ steps.access_token.outputs.token }}
          path: builder

      # New get date
      - name: Get current time/date
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDD

      - name: Build Document
        timeout-minutes: 30
        env:
          NOW: "${{ steps.current-time.outputs.formattedTime }}"
          version:      ${{env.DOCUMENT_VERSION}}
          filename:     ${{env.DOCUMENT_FILE_NAME}} 
          configfile:   ${{env.CONFIG_FILE}}
        run: >
          python ..\builder\specbuilder.py $env:configfile
          "$env:filename $env:version DRAFT-$env:NOW Build-$env:GITHUB_RUN_NUMBER"
          "$env:version DRAFT-$env:NOW Build-$env:GITHUB_RUN_NUMBER"
          "Run-$env:GITHUB_RUN_NUMBER"
        working-directory: ./document

      # Upload any artefact produced.
      - name: Upload Document
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}-artifact
          path: document/target/*.pdf
          
      # Upload to Confluence
      - name: Confluence Upload
        uses: cip4/action-confluence-upload@master
        with:
          url: 'https://confluence.cip4.org'
          username: ${{ secrets.CONFLUENCE_USER }}
          password: ${{ secrets.CONFLUENCE_PASSWORD }}
          contentId: ${{ env.CONFLUENCE_ID }}
          label: ${{ env.CONFLUENCE_LABELS }}
          filePattern: 'document/target/*.pdf'
